# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: alluxio-operator-monitor
  name: alluxio-operator-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      -alluxio-operator
  selector:
    matchLabels:
      k8s-app: alluxio-operator