name: Alluxio Helm Chart Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Helm Chart Render Templates Check
        run: tests/helm/verifyTemplates.sh
        timeout-minutes: 1

      - name: Operator Structs Check
        run: go run tests/helm/verifyStruct.go
        timeout-minutes: 5

      - name: Archive result templates
        continue-on-error: true
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: result templates
          path: tests/helm/resultTemplates
          retention-days: 7

      - name: Download result templates
        uses: actions/download-artifact@v3